### ISSUE TITLE
Invalid preflight CORS reuqest because the header "accept" is not in :allow_headers

### ISSUE THREAD

**Issue by justinbkay** [whatyouhide/corsica#10]
When using this library with Ember.js, simple CORS requests work, but preflight requests won't work. Is this because of a bug in Ember-Cli and it's implementation of CORS, or is there something that I'm missing?  I've tried using it as a Plug and as a Corsica.Router. Same results.

**Comment by whatyouhide** [comment]
Hey there! So I'm not sure I understood what you're saying: did you put the `"accept"` header in the list of `:allow_headers` and it still didn't work?

**Comment by justinbkay** [comment]
Doesn't the client supply that?  From the error, it looks like the request
from Ember.js was not being accepted by the Plug.  I don't know if there is
anything that I could do on the Elixir side to make it work.

On Thu, Nov 19, 2015 at 2:23 AM, Andrea Leopardi <notifications@github.com>
wrote:

> Hey there! So I'm not sure I understood what you're saying: did you put
> the "accept" header in the list of :allow_headers and it still didn't
> work?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/whatyouhide/corsica/issues/10#issuecomment-157998689>.
>



-- 
Sites:
http://jbkayconstruction.com
https://twitter.com/justinbkay
http://justinbkay.tumblr.com

It always takes longer than you expect, even when you take into account
Hofstadter’s Law.
- Hofstadter’s Law

**Comment by whatyouhide** [comment]
@justinbkay with CORS, when the server replies to a preflight request, it should include an `access-control-allow-headers` header. This header contains a list of header names that are allowed in the subsequent CORS request (the one this preflight request was made for). In the preflight request, the client specifies the `access-control-request-headers` header with a list of headers that will be used in subsequent requests (it's basically asking if it can use those headers, and the server is replying yes/no).

By default, Corsica doesn't specify any headers in the `access-control-allow-headers` header (because `:allow_headers` - a Corsica configuration option - is `[]` by default). This means that when the request comes in with `Accept` in the `access-control-request-headers` header, Corsica looks at the `:allow_header` list and sees the `Accept` header is not in there: the CORS request is thus invalid.

I ranted long enough (sorry :smile:), but putting `"accept"` in the `:allow_headers` list when using Corsica. For example, using Corsica as a plug:

```elixir
plug Corsica, allow_headers: ["accept"]
```

**Comment by justinbkay** [comment]
Thanks for taking the time to clarify that.  The error message left me a
little bit confused as to how to overcome the issue.

On Fri, Nov 20, 2015 at 9:09 AM, Andrea Leopardi <notifications@github.com>
wrote:

> @justinbkay <https://github.com/justinbkay> with CORS, when the server
> replies to a preflight request, it should include an
> access-control-allow-headers header. This header contains a list of
> header names that are allowed in the subsequent CORS request (the one this
> preflight request was made for). In the preflight request, the client
> specifies the access-control-request-headers header with a list of
> headers that will be used in subsequent requests (it's basically asking if
> it can use those headers, and the server is replying yes/no).
>
> By default, Corsica doesn't specify any headers in the
> access-control-allow-headers header (because :allow_headers - a Corsica
> configuration option - is [] by default). This means that when the
> request comes in with Accept in the access-control-request-headers
> header, Corsica looks at the :allow_header list and sees the Accept
> header is not in there: the CORS request is thus invalid.
>
> I ranted long enough (sorry [image: :smile:]), but putting "accept" in
> the :allow_headers list when using Corsica. For example, using Corsica as
> a plug:
>
> plug Corsica, allow_headers: ["accept"]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/whatyouhide/corsica/issues/10#issuecomment-158445517>.
>



-- 
Sites:
http://jbkayconstruction.com
https://twitter.com/justinbkay
http://justinbkay.tumblr.com

It always takes longer than you expect, even when you take into account
Hofstadter’s Law.
- Hofstadter’s Law

**Comment by whatyouhide** [comment]
@justinbkay you mean the error message in the browser right? If any error message from Corsica left you confused than that's a Corsica bug that we should solve :)

**Comment by justinbkay** [comment]
It was the debug logging in Corsica that left me confused.  I thought that
Ember wasn't sending something that it was supposed to send.  It's
difficult to remember now as I was in a state of frustration at it not
working.

On Fri, Nov 20, 2015 at 9:13 AM, Andrea Leopardi <notifications@github.com>
wrote:

> @justinbkay <https://github.com/justinbkay> you mean the error message in
> the browser right? If any error message from Corsica left you confused than
> that's a Corsica bug that we should solve :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/whatyouhide/corsica/issues/10#issuecomment-158446790>.
>



-- 
Sites:
http://jbkayconstruction.com
https://twitter.com/justinbkay
http://justinbkay.tumblr.com

It always takes longer than you expect, even when you take into account
Hofstadter’s Law.
- Hofstadter’s Law

**Comment by justinbkay** [comment]
So this is what I'm getting in the browser:

XMLHttpRequest cannot load http://localhost:4000/posts. Response to
preflight request doesn't pass access control check: No
'Access-Control-Allow-Origin' header is present on the requested resource.
Origin 'http://localhost:4200' is therefore not allowed access. The
response had HTTP status code 404.
ember.debug.js:33441 Error: Adapter operation failed
    at new Error (native)
    at Error.EmberError (http://localhost:4200/assets/vendor.js:27241:21)
    at Error.ember$data$lib$adapters$errors$$AdapterError (
http://localhost:4200/assets/vendor.js:70955:50)
    at ember$data$lib$system$adapter$$default.extend.handleResponse (
http://localhost:4200/assets/vendor.js:72673:16)
    at hash.error (http://localhost:4200/assets/vendor.js:72769:33)
    at fire (http://localhost:4200/assets/vendor.js:3350:30)
    at Object.self.fireWith [as rejectWith] (
http://localhost:4200/assets/vendor.js:3462:7)
    at done (http://localhost:4200/assets/vendor.js:9518:14)
    at XMLHttpRequest.callback (
http://localhost:4200/assets/vendor.js:9920:8)onerrorDefault @
ember.debug.js:33441exports.default.trigger @
ember.debug.js:57651Promise._onerror @ ember.debug.js:58617publishRejection
@ ember.debug.js:56924(anonymous function) @
ember.debug.js:33402Queue.invoke @ ember.debug.js:910Queue.flush @
ember.debug.js:974DeferredActionQueues.flush @
ember.debug.js:770Backburner.end @ ember.debug.js:160Backburner.run @
ember.debug.js:228run @ ember.debug.js:21027hash.error @
rest-adapter.js:860fire @ jquery.js:3148self.fireWith @ jquery.js:3260done
@ jquery.js:9316callback @ jquery.js:9718

The simple cors request is working fine.

This is my plug line in a Phoenix app:

plug Corsica, [origins: ["http://localhost:4200"], allow_headers:
["accept"]]




On Fri, Nov 20, 2015 at 9:13 AM, Andrea Leopardi <notifications@github.com>
wrote:

> @justinbkay <https://github.com/justinbkay> you mean the error message in
> the browser right? If any error message from Corsica left you confused than
> that's a Corsica bug that we should solve :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/whatyouhide/corsica/issues/10#issuecomment-158446790>.
>



-- 
Sites:
http://jbkayconstruction.com
https://twitter.com/justinbkay
http://justinbkay.tumblr.com

It always takes longer than you expect, even when you take into account
Hofstadter’s Law.
- Hofstadter’s Law

**Comment by whatyouhide** [comment]
What are the headers you're sending in the browser?

**Comment by justinbkay** [comment]
I'm not doing anything, it is just what ember.js sends.  If there is a way
to log that from the Corsica side, I'll gladly do that and relay them to
you.

On Fri, Nov 20, 2015 at 9:50 AM, Andrea Leopardi <notifications@github.com>
wrote:

> What are the headers you're sending in the browser?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/whatyouhide/corsica/issues/10#issuecomment-158457413>.
>



-- 
Sites:
http://jbkayconstruction.com
https://twitter.com/justinbkay
http://justinbkay.tumblr.com

It always takes longer than you expect, even when you take into account
Hofstadter’s Law.
- Hofstadter’s Law

**Comment by whatyouhide** [comment]
Ok, you can either `IO.inspect(conn)` somewhere before your `plug Corsica, ...` line (e.g., create a new plug and add it to the pipeline) or just look at the request Ember makes in the "Network" tab of the Chrome dev tools (or your browser of choice's alternative).

If you go with the plug (I'd say for convenience just look at the dev tools, but still), try something like this:

```elixir
plug :inspect_conn
plug Corsica, ...

defp inspect_conn(conn, _), do: IO.inspect(conn)
```

**Comment by justinbkay** [comment]
OPTIONS /posts HTTP/1.1
Host: localhost:4000
Connection: keep-alive
Access-Control-Request-Method: POST
Origin: http://localhost:4200
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_5)
AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.86 Safari/537.36
Access-Control-Request-Headers: accept, content-type
Accept: */*
Referer: http://localhost:4200/posts/new
Accept-Encoding: gzip, deflate, sdch
Accept-Language: en-US,en;q=0.8

On Fri, Nov 20, 2015 at 9:55 AM, Andrea Leopardi <notifications@github.com>
wrote:

> Ok, you can either IO.inspect(conn) somewhere before your plug Corsica,
> ... line (e.g., create a new plug and add it to the pipeline) or just
> look at the request Ember makes in the "Network" tab of the Chrome dev
> tools (or your browser of choice's alternative).
>
> If you go with the plug (I'd say for convenience just look at the dev
> tools, but still), try something like this:
>
> plug :inspect_conn
> plug Corsica, ...
> defp inspect_conn(conn, _), do: IO.inspect(conn)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/whatyouhide/corsica/issues/10#issuecomment-158458486>.
>



-- 
Sites:
http://jbkayconstruction.com
https://twitter.com/justinbkay
http://justinbkay.tumblr.com

It always takes longer than you expect, even when you take into account
Hofstadter’s Law.
- Hofstadter’s Law

**Comment by whatyouhide** [comment]
Ok as you can see, you/Ember are sending both `accept` and `content-type` as the headers in `access-control-request-headers`. As I said before, you have to list all these headers in the `:allow_headers` option in order for the request to be allowed.

```elixir
plug Corsica, allow_headers: ["accept", "content-type"]
```

**Comment by justinbkay** [comment]
Still no dice:

plug Corsica, [origins: ["http://localhost:4200"], allow_headers:
["accept", "content-type"]]

Browser Error:
XMLHttpRequest cannot load http://localhost:4000/posts. Response to
preflight request doesn't pass access control check: No
'Access-Control-Allow-Origin' header is present on the requested resource.
Origin 'http://localhost:4200' is therefore not allowed access. The
response had HTTP status code 404.

Headers:
OPTIONS /posts HTTP/1.1
Host: localhost:4000
Connection: keep-alive
Access-Control-Request-Method: POST
Origin: http://localhost:4200
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_5)
AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.86 Safari/537.36
Access-Control-Request-Headers: accept, content-type
Accept: */*
Referer: http://localhost:4200/posts/new
Accept-Encoding: gzip, deflate, sdch
Accept-Language: en-US,en;q=0.8


On Fri, Nov 20, 2015 at 10:11 AM, Andrea Leopardi <notifications@github.com>
wrote:

> Ok as you can see, you/Ember are sending both accept and content-type as
> the headers in access-control-request-headers. As I said before, you have
> to list all these headers in the :allow_headers option in order for the
> request to be allowed.
>
> plug Corsica, allow_headers: ["accept", "content-type"]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/whatyouhide/corsica/issues/10#issuecomment-158462598>.
>



-- 
Sites:
http://jbkayconstruction.com
https://twitter.com/justinbkay
http://justinbkay.tumblr.com

It always takes longer than you expect, even when you take into account
Hofstadter’s Law.
- Hofstadter’s Law

**Comment by whatyouhide** [comment]
@justinbkay mmm, ok. What are the logs from Corsica?

**Comment by justinbkay** [comment]
info] Running PeepBlogBackend.Endpoint with Cowboy on http://localhost:4000
Interactive Elixir (1.1.1) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> [info] GET /posts
[debug] Simple CORS request from Origin 'http://localhost:4200' is allowed
[debug] Processing by PeepBlogBackend.PostController.index/2
  Parameters: %{}
  Pipelines: [:api]
[debug] SELECT p0."id", p0."title", p0."body", p0."inserted_at",
p0."updated_at" FROM "posts" AS p0 [] OK query=139.4ms queue=3.6ms
[info] Sent 200 in 216ms
20 Nov 10:20:37 - info: compiled 7 files into 2 files, copied 3 in 2474ms
[info] OPTIONS /posts


On Fri, Nov 20, 2015 at 10:17 AM, Andrea Leopardi <notifications@github.com>
wrote:

> @justinbkay <https://github.com/justinbkay> mmm, ok. What are the logs
> from Corsica?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/whatyouhide/corsica/issues/10#issuecomment-158464153>.
>



-- 
Sites:
http://jbkayconstruction.com
https://twitter.com/justinbkay
http://justinbkay.tumblr.com

It always takes longer than you expect, even when you take into account
Hofstadter’s Law.
- Hofstadter’s Law

**Comment by whatyouhide** [comment]
Ok, looks like Corsica thinks this is a valid CORS req (btw, this is a simple CORS req, not the preflight we were talking about earlier). Could you show me the response headers that the browser gets?

**Comment by justinbkay** [comment]
Response headers:

HTTP/1.1 404 Not Found
server: Cowboy
date: Fri, 20 Nov 2015 17:20:40 GMT
content-length: 43412
cache-control: max-age=0, private, must-revalidate
content-type: text/html; charset=utf-8

On Fri, Nov 20, 2015 at 10:34 AM, Andrea Leopardi <notifications@github.com>
wrote:

> Ok, looks like Corsica thinks this is a valid CORS req (btw, this is a
> simple CORS req, not the preflight we were talking about earlier). Could
> you show me the response headers that the browser gets?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/whatyouhide/corsica/issues/10#issuecomment-158468040>.
>



-- 
Sites:
http://jbkayconstruction.com
https://twitter.com/justinbkay
http://justinbkay.tumblr.com

It always takes longer than you expect, even when you take into account
Hofstadter’s Law.
- Hofstadter’s Law

**Comment by whatyouhide** [comment]
@justinbkay ok, sorry for the delay. So, I can't spot anything wrong, it should work :\ Let's try this instead: first, could you show me your plug pipeline in `endpoint.ex`? Also, let's try to inspect the connection after Corsica gets called. Place this in the endpoint and paste the output here:

```elixir
plug Corsica, ...
plug :inspect_conn

# at the end of the file
defp inspect_conn(conn, _), do: IO.inspect(conn)
```

(btw, I'm `whatyouhide` on the `#elixir-lang` IRC channel if you want to speed things up a little bit :))

**Comment by justinbkay** [comment]
[info] GET /posts
[debug] Simple CORS request from Origin 'http://localhost:4200' is allowed
%Plug.Conn{adapter: {Plug.Adapters.Cowboy.Conn, :...}, assigns: %{},
 before_send: [#Function<1.1051886/1 in Plug.Logger.call/2>,
  #Function<0.116139981/1 in
Phoenix.LiveReloader.before_send_inject_reloader/1>],
 body_params: %{}, cookies: %Plug.Conn.Unfetched{aspect: :cookies},
 halted: false, host: "localhost", method: "GET", owner: #PID<0.380.0>,
 params: %{}, path_info: ["posts"], peer: {{127, 0, 0, 1}, 62130}, port:
4000,
 private: %{PeepBlogBackend.Router => {[], %{}},
   :phoenix_endpoint => PeepBlogBackend.Endpoint, :phoenix_format => "json",
   :phoenix_pipelines => [:api],
   :phoenix_route => #Function<7.14635622/1 in
PeepBlogBackend.Router.match/4>,
   :phoenix_router => PeepBlogBackend.Router,
   :plug_session_fetch => #Function<0.14684344/1 in
Plug.Session.fetch_session/1>},
 query_params: %{}, query_string: "", remote_ip: {127, 0, 0, 1},
 req_cookies: %Plug.Conn.Unfetched{aspect: :cookies},
 req_headers: [{"host", "localhost:4000"}, {"connection", "keep-alive"},
  {"cache-control", "max-age=0"},
  {"accept", "application/json, text/javascript, */*; q=0.01"},
  {"origin", "http://localhost:4200"},
  {"user-agent",
   "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_5) AppleWebKit/537.36
(KHTML, like Gecko) Chrome/46.0.2490.86 Safari/537.36"},
  {"referer", "http://localhost:4200/posts/new"},
  {"accept-encoding", "gzip, deflate, sdch"},
  {"accept-language", "en-US,en;q=0.8"}], request_path: "/posts",
 resp_body: nil, resp_cookies: %{},
 resp_headers: [{"cache-control", "max-age=0, private, must-revalidate"},
  {"x-request-id", "5h58qg0eokf2ikqcaiicqaj3c7ao2481"},
  {"access-control-allow-origin", "http://localhost:4200"}], scheme: :http,
 script_name: [],
 secret_key_base:
"O/fW8oQ1TqD4PYaT4eC7NB2iQNgit7T10dbUlfUgVfY2N6szP1wdhPs8K3NQ1GH1",
 state: :unset, status: nil}
[debug] Processing by PeepBlogBackend.PostController.index/2
  Parameters: %{}
  Pipelines: [:api]
[debug] SELECT p0."id", p0."title", p0."body", p0."inserted_at",
p0."updated_at" FROM "posts" AS p0 [] OK query=149.9ms queue=6.2ms
[info] Sent 200 in 251ms
[info] OPTIONS /posts
[info] GET /posts

**Comment by whatyouhide** [comment]
Ok, this is a simple CORS request so the response has no `access-control-allow-headers` header; it has just an `access-control-allow-origin` header which is set to the correct value (`http://localhost:4200`).

This response is not a response to the request you showed me earlier though. As you can see in the log, it's a `GET /posts` request and after the connection is printed it says `Sent 200 in 251ms`, so the response is a 200 OK response (while you showed a 404 response). :\

**Comment by justinbkay** [comment]
I'm hitting a save button which posts to /posts

failed request:

OPTIONS /posts HTTP/1.1
Host: localhost:4000
Connection: keep-alive
Access-Control-Request-Method: POST
Origin: http://localhost:4200
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_5)
AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.86 Safari/537.36
Access-Control-Request-Headers: accept, content-type
Accept: */*
Referer: http://localhost:4200/posts/new
Accept-Encoding: gzip, deflate, sdch
Accept-Language: en-US,en;q=0.8

response:

Remote Address:127.0.0.1:4000
Request URL:http://localhost:4000/posts
Request Method:OPTIONS
Status Code:404 Not Found

The only thing that gets logged by Phoenix is:
[info] OPTIONS /posts




On Fri, Nov 20, 2015 at 11:37 AM, Andrea Leopardi <notifications@github.com>
wrote:

> Ok, this is a simple CORS request so the response has no
> access-control-allow-headers header; it has just an
> access-control-allow-origin header which is set to the correct value (
> http://localhost:4200).
>
> This response is not a response to the request you showed me earlier
> though. As you can see in the log, it's a GET /posts request and after
> the connection is printed it says Sent 200 in 251ms, so the response is a
> 200 OK response (while you showed a 404 response). :\
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/whatyouhide/corsica/issues/10#issuecomment-158485474>.
>



-- 
Sites:
http://jbkayconstruction.com
https://twitter.com/justinbkay
http://justinbkay.tumblr.com

It always takes longer than you expect, even when you take into account
Hofstadter’s Law.
- Hofstadter’s Law

**Comment by whatyouhide** [comment]
Ok, so that doesn't look like a Corsica problem though! I mean, Corsica doesn't send 404s, ever. Since you can't show me the plug pipeline I'll have to ask if Corsica is placed before or after your router?

**Comment by justinbkay** [comment]
In:

pipeline :api do
    plug :accepts, ["json"]

    plug Corsica, [origins: ["http://localhost:4200"], allow_headers:
["accept", "content-type"], log: :debug]
    plug :inspect_conn
  end

On Fri, Nov 20, 2015 at 12:08 PM, Andrea Leopardi <notifications@github.com>
wrote:

> Ok, so that doesn't look like a Corsica problem though! I mean, Corsica
> doesn't send 404s, ever. Since you can't show me the plug pipeline I'll
> have to ask if Corsica is placed before or after your router?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/whatyouhide/corsica/issues/10#issuecomment-158496931>.
>



-- 
Sites:
http://jbkayconstruction.com
https://twitter.com/justinbkay
http://justinbkay.tumblr.com

It always takes longer than you expect, even when you take into account
Hofstadter’s Law.
- Hofstadter’s Law

**Comment by justinbkay** [comment]
defmodule PeepBlogBackend.Endpoint do
..
  plug Corsica, [origins: ["http://localhost:4200"], allow_headers:
["accept", "content-type"], log: :debug]
  plug PeepBlogBackend.Router
end

If I place the plug in the Endpoint before the router I get this in the
browser:

XMLHttpRequest cannot load http://localhost:4000/posts. No
'Access-Control-Allow-Origin' header is present on the requested resource.
Origin 'http://localhost:4200' is therefore not allowed access.


Which means that even simple cors requests don't work.

I was just trying to follow this tutorial
http://maxwellholder.com/blog/build-a-blog-with-phoenix-and-ember by the
way.  The PlugCors lib was not working and deprecated, that's how I found
Corsica.



On Fri, Nov 20, 2015 at 12:08 PM, Andrea Leopardi <notifications@github.com>
wrote:

> Ok, so that doesn't look like a Corsica problem though! I mean, Corsica
> doesn't send 404s, ever. Since you can't show me the plug pipeline I'll
> have to ask if Corsica is placed before or after your router?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/whatyouhide/corsica/issues/10#issuecomment-158496931>.
>



-- 
Sites:
http://jbkayconstruction.com
https://twitter.com/justinbkay
http://justinbkay.tumblr.com

It always takes longer than you expect, even when you take into account
Hofstadter’s Law.
- Hofstadter’s Law

**Comment by justinbkay** [comment]
RESOLVED!!!!

Ok, moving the plug before the router and restarting the server fixed it.
I definitely needed the allow_headers, but I put the plug in the wrong spot
today.  I'm positive I tried it before the router yesterday.

On Fri, Nov 20, 2015 at 12:08 PM, Andrea Leopardi <notifications@github.com>
wrote:

> Ok, so that doesn't look like a Corsica problem though! I mean, Corsica
> doesn't send 404s, ever. Since you can't show me the plug pipeline I'll
> have to ask if Corsica is placed before or after your router?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/whatyouhide/corsica/issues/10#issuecomment-158496931>.
>



-- 
Sites:
http://jbkayconstruction.com
https://twitter.com/justinbkay
http://justinbkay.tumblr.com

It always takes longer than you expect, even when you take into account
Hofstadter’s Law.
- Hofstadter’s Law

**Comment by whatyouhide** [comment]
@justinbkay hey there, ok happy you managed to solve this :) Yes when I asked you where the plug was I was almost sure it was after the router, which is why you get 404s with `OPTIONS` requests. I'll mention you also can't plug Corsica *inside* the router just to be a little clearer :)

**Comment by justinbkay** [comment]
Thanks for working with me.  I submitted a patch to that tutorial to switch
from PlugCors to Corsica.  Hopefully it gets accepted.

On Sat, Nov 21, 2015 at 5:36 AM, Andrea Leopardi <notifications@github.com>
wrote:

> Closed #10 <https://github.com/whatyouhide/corsica/issues/10>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/whatyouhide/corsica/issues/10#event-471183424>.
>



-- 
Sites:
http://jbkayconstruction.com
https://twitter.com/justinbkay
http://justinbkay.tumblr.com

It always takes longer than you expect, even when you take into account
Hofstadter’s Law.
- Hofstadter’s Law

**Comment by whatyouhide** [comment]
@justinbkay thanks a lot! :heart_decoration: I updated the docs for Corsica mentioning to put the plug before and *outside* of routers like `Phoenix.Router` in the meantime :)

**Comment by divmgl** [comment]
Thanks to this issue, I was able to figure out that you need to specify what headers can be sent through a CORS preflight. Thanks guys.

**Comment by alanwilhelm** [comment]
Dumping the headers and adding them to allow in the plug config worked for me. I literally have to read this every time I start a new proj.
