### ISSUE TITLE
Spelling error

### ISSUE THREAD

**Issue by combsco** [whatyouhide/corsica#11]
[info] Invalid preflight CORS **reuqest** because the header

**Comment by whatyouhide** [comment]
Hey, nice catch! Are you willing to open a PR? Otherwise I can take care of it :).

**Comment by hunterboerner** [comment]
@whatyouhide I don't think he's going to open a PR.

**Comment by whatyouhide** [comment]
@hunterboerner probably not :smile: Taking care of it now.

**Comment by whatyouhide** [comment]
Ooops, this was already fixed in #7, I just forgot to release a new version :).

**Comment by whatyouhide** [comment]
Released v0.4.1!
