### ISSUE TITLE
Doc: mention in Readme that regex is allowed

### ISSUE THREAD

**Issue by pinx** [whatyouhide/corsica#14]
It took me some digging in the docs, to find out that I can replace the string after "origins:" with a regex like ~r{//localhost} to make it match any protocol or port. NB: Elixir docs suggest using ~r{..} syntax for regex, so you don't have to escape "/"s
This is one of the first things a new user will look for, so it deserves a place in the README.

**Comment by whatyouhide** [comment]
Closed in e06e62de4d1aa1b35b01993773432893b3552575.
