### ISSUE TITLE
No CORS headers on statically served files

### ISSUE THREAD

**Issue by madshargreave** [whatyouhide/corsica#16]
Hi

I have enabled Corsica in my Endpoint as such:

```
plug Corsica, max_age: 600, origins: "*", log: :info, allow_headers: ["accept", "content-type", "authorization", "origin"]
```

And If I make any requests to my domain, I see the correct `access-control-allow-origin: *` header.

However, if I request asses such as fonts, the header is not set

Why is this?

UPDATE:

Making any non-staticfile requests to the server logs:

```
Simple CORS request from Origin 'http://gitchecker.com' is allowed
HEAD /some_non_asset_path
```

If I request an asset, nothing is logged

**Comment by whatyouhide** [comment]
It seems likely that the plug that serves static files comes before `Corsica` in the plug pipeline. Could that be the case?

**Comment by madshargreave** [comment]
Indeed it did and moving it fixed the problem. Much appreciated

**Comment by whatyouhide** [comment]
@madshargreave no worries, my pleasure :)
