### ISSUE TITLE
Could you create a new release with the code style fixes?

### ISSUE THREAD

**Issue by samueljseay** [whatyouhide/corsica#20]
Elixir 1.3 warns about route being an unsafe var in the current release of Corsica. I can see that you fixed it [here](https://github.com/whatyouhide/corsica/commit/d21d16f795fce6550964271ba9006d18403b9a42#diff-6994978eb9b2a11415861feb81985fc1R111)

I was wondering if we could get a release with this fix?

Thanks for building Corsica, I've enjoyed using it :)

**Comment by whatyouhide** [comment]
Version `v0.5.0` has been released [on Hex](https://hex.pm/packages/corsica). 👍
