### ISSUE TITLE
SyntaxError when using Corsica.Router (v0.5.0)

### ISSUE THREAD

**Issue by GabrielMangiurea** [whatyouhide/corsica#26]
Hello, everyone!

I am getting a SyntaxError when using Corsica.Router with the usage example found in the documentation:
```
defmodule MyApp.CORS do
  use Corsica.Router,
    origins: ["http://localhost", ~r{^https?://(.*\.?)foo\.com$}],
    allow_credentials: true,
    max_age: 600,

  resource "/public/*", origins: "*"
  resource "/*"
end

defmodule MyApp.Endpoint do
  plug Logger
  plug MyApp.CORS
  plug MyApp.Router
end
```

```
== Compilation error on file lib/myapp/cors.ex ==
** (SyntaxError) lib/myapp/cors.ex:7: syntax error before: resource
    (elixir) lib/kernel/parallel_compiler.ex:117: anonymous fn/4 in Kernel.ParallelCompiler.spawn_compilers/1
```

The Corsica plug, however, works fine.
I am using Corsica **0.5.0**.

Thank you!

**Comment by whatyouhide** [comment]
You have a comma after the `max_age: 600` property. It is of course my fault as that is what the example in the README has :( Sorry for the trouble, pushed a fix in ece6846. Thanks for the report! 💟
