### ISSUE TITLE
Ability to allow all headers

### ISSUE THREAD

**Issue by nsweeting** [whatyouhide/corsica#30]
It would be nice to allow all headers with something like:

` plug Corsica, [allow_headers: :all]`

**Comment by whatyouhide** [comment]
What's your use case?

**Comment by buhman** [comment]
I think related to #31, it makes sense to have an easily-visible option/default to add the `simple headers` (and `content-type`) from the spec.

**Comment by whatyouhide** [comment]
Closed in 38b7d6d40de58b5c6046d3bb6e7aa1cd884b9302.
