### ISSUE TITLE
Provide an :always option to use without Origin Header

### ISSUE THREAD

**Issue by webdeb** [whatyouhide/corsica#32]
Hi, corsica is really cool while developing, but you have to include the Origin Header from the client, even if later in production you will server the app from the main origin anyway.

I though, that maybe it will be helpful to ovoid that restriction explicitly with a simple option like `:always`

Especially for my current project the case for CORS is only in :dev, and would look something like this:

```
// endpoint.ex
...
if (Mix.env == :dev) do
  plug Corsica, origins: "*", always: true
end
```

**Comment by whatyouhide** [comment]
Hey @webdeb, what if you did this with a custom plug before Corsica instead?

```elixir
if Mix.env() == :dev do
  plug :add_origin_header
end

plug Corsica, ...

defp add_origin_header(conn, _opts) do
  put_req_header(conn, "origin", "http://example.com")
end
```

I can't think of many use cases for your `:always` so this seems like a flexible solution.

**Comment by webdeb** [comment]
Well.. yeah, I think I could do this as well, thank you :)
