### ISSUE TITLE
resource "/*" results in compiler warning with Corsica.Router

### ISSUE THREAD

**Issue by techgaun** [whatyouhide/corsica#36]
Because of this match-all: https://github.com/whatyouhide/corsica/blob/b189d3e8e6936defb4559d93a8e60308531de982/lib/corsica/router.ex#L140-L142

compiler warnings happen when we use `Corsica.Router` module as below:

```
defmodule CustomCORS do
  use Corsica.Router,
    origins: ["https://example.com"]

  resource "/*"
end
```

Example warning:
```
warning: this clause cannot match because a previous clause at line 5 always matches
  test/corsica/router_test.exs:5
```

Based on brief look, something like below may work I guess but not sure if thats the best way to handle:

```
      has_match_all? = Enum.find_value(routes, false, fn {r, _} -> r === "/*" end)
 
      unless has_match_all? do
        # Match-all clause that just returns the connection unchanged.
        match _ do
          var!(conn)
        end
      end
```

The reason I am opening this issue is because I am using `mix compile --warnings-as-errors`. Any thoughts on how to best handle this?

**Comment by whatyouhide** [comment]
Good catch! The solution you proposed sounds good. Can you please send a PR?

Also, use `Enum.any?/2` instead of `Enum.find_value/3`.
