### ISSUE TITLE
No headers when the request is invalid, always

### ISSUE THREAD

**Issue by whatyouhide** [whatyouhide/corsica#4]
Right now, if a request is made and the origin isn't in the whitelist of origins, As per the [relevant section of the W3C CORS spec](http://www.w3.org/TR/cors/#resource-processing-model), if the request has something wrong (whether it's a non valid origin or request method or request headers and so on), **no `Access-Control-*` headers should be returned**. The browser will automatically take care of interpreting this as an error.

A bunch of advantages I thought of:
- smaller response (I'm talking about the response size)
- less information given on what the accepted origins are
- simpler logic and options since we can nuke the `:allow_origin` option altogether

**Comment by blacksails** [comment]
Hmm i spent a few hours today trying to make angular work with your project. It is hard for the user to figure out what is going on, or why some request doesn't return any Access-Control-* headers. Maybe it would be cool to be able to toggle some debug logging, so that it's easier to find out why no Access-Control-* headers are returned. This could be something like why some request is deemed invalid.

Appart from this i really like the work you have put into this project!

**Comment by whatyouhide** [comment]
Hey @blacksails, thanks so much for the bug report (and the nice words :heart:)!

So, as I said in the issue, the reason behind not returning any `Access-Control-*` headers is compliance with the W3C CORS spec I linked above. That said, you're absolutely right here and this behaviour is probably very obscure for a user of this library; logging is a great idea, I'll add the functionality as soon as I can!

Sorry for the few hours you lost because of this :(

As an aside, may I ask you how you're using this library? Are you using `Corsica` as a plug (like `plug Corsica, ...` or as a router generator (`use Corsica`)? It would be nice to get some insight on how this library is used by actual users :). Thanks!

**Comment by blacksails** [comment]
I used it as router generator. It seems cool to have control over how CORS should be handled in different parts of an API. One could imagine that some parts of an API would be used internally and other parts would maybe be public, with your router generator it is very easy to do something like that. :+1:

**Comment by whatyouhide** [comment]
Hi @blacksails, I pushed a couple of new commits which include the logging functionality we discussed here. Would you be willing to try out the `master` branch and tell me what you think? If you think this solves the problem I can push a new version to hex.pm.

To use the `master` just list the `:corsica` dependency as

```elixir
[...,
 {:corsica, github: "whatyouhide/corsica"}]
```

and to use logging add

```elixir
config :corsica, log_level: :info
```

to your `config/config.exs`. Thanks for all the help! :)
