### ISSUE TITLE
paytm integration with ionic application 

### ISSUE THREAD

**Issue by kumarkvinoth** [whatyouhide/corsica#41]
Hi guys, 
    I was integrate paytm to my ionic application . i have some error to redirect to the paytm server. 
### **my code is** 

`var headers = new Headers();
  headers.append("Accept", 'application/json');
  headers.append('Content-Type', 'application/json' );
 
  let postData = {
          "MID":"XXXXXXXXXX",
          "ORDER_ID" :"ORDERVK002",
          "CUST_ID":"10000988111",
          "TXN_AMOUNT":"1",
          "CHANNEL_ID":"WAP",
          "INDUSTRY_TYPE_ID" :"Retail",
          "WEBSITE":"APP_STAGING",
          "CHECKSUMHASH":"EnUKKBreoyyh0fBcHo4FGk4iVJfDylyeJgo6W9LzHMFRuGDyl4+Pp6ZztOJK+6vwwymScNEyUd++V3IYtEvRouYWOA+Mp6bPbFG2YjEKU3k=",
          "MOBILE_NO":"98655XXXX",
          "EMAIL":"XXXXX@gmail.com"
  }
  this.http.post("https://securegw-stage.paytm.in/theia/processTransaction", postData, {headers:headers})
    .subscribe( res =>
       console.log(res)); 
   }`

### **i was run that code i am getting below error response**

Failed to load resource: the server responded with a status of 403 (Forbidden)
(index):1 Failed to load https://securegw-stage.paytm.in/theia/processTransaction: Response for preflight does not have HTTP ok status.
vendor.js:1823 ERROR Response

how to resolve this issue , thankyou

**Comment by whatyouhide** [comment]
It's hard to debug this with only the information provided. You would need to provide code that shows how you are using Corsica. However, there's a chance that the error is that you're not including any CORS headers in your request (like `Origin`).

I'll close this for insufficient information, but please feel free to reopen as soon as you can provide more details. Thanks!
