### ISSUE TITLE
SameSite header

### ISSUE THREAD

**Issue by slashmili** [whatyouhide/corsica#46]
Hi, 

Chrome has introduces a new header to secure cookies and I'm wondering if it fits this module to handle that([read more](https://blog.chromium.org/2019/10/developers-get-ready-for-new.html))

If you agree that this is something we can cover in Corsica, it could look like this:

```elixir
defmodule MyApp.CORS do
  use Corsica.Router,
    origins: ["http://localhost", ~r{^https?://(.*\.?)foo\.com$}],
    allow_credentials: true,
    same_site: "None; secure",
    max_age: 600
```

I don't like the value of `same_site` being string but don't have any other suggestion right now.

**Comment by whatyouhide** [comment]
`SameSite` is part of the `Set-Cookie` header, right? I'm not sure how it fits in a CORS-focused library. Can you elaborate on that? Thanks!

**Comment by slashmili** [comment]
You are correct. I though it's a separate header!

Anyway thanks for the quick response!
