### ISSUE TITLE
Clarify that `Plug.Static` is a router for CORS purposes

### ISSUE THREAD

**Issue by halostatue** [whatyouhide/corsica#48]
The Corsica documentation is pretty clear that it must be higher than your router, which is good. I discovered today that this includes `Plug.Static`.

There are three places that I think this is worth clarifying by either mentioning that `Plug.Static` needs to be after Corsica or Corsica routers.

1. Around [corsica/router.ex:38](https://github.com/whatyouhide/corsica/blob/cca8615d4f29f5ee17b82d199b37ec7d82d51594/lib/corsica/router.ex#L38).
2. Around [corsica.ex:45-55](https://github.com/whatyouhide/corsica/blob/6d9b90f1087501cfc4a243ebafbc976a9f7c5085/lib/corsica.ex#L45-L55).
3. Around [pages/Common Issues.md:13-15](https://github.com/whatyouhide/corsica/blob/07c579c50ec373015e3df9ca8e1bdadbc8e65d41/pages/Common%20issues.md#L13-15).

For the latter, I would suggest something like:

```markdown
The Corsica plug is lower than any handling router in your plug pipeline (such as `Plug.Router`, a `Phoenix.Router`, or `Plug.Static`).
```

**Comment by whatyouhide** [comment]
Good calls, fixed :) Thank you @halostatue! 💟
