### ISSUE TITLE
Misleading docs.

### ISSUE THREAD

**Issue by hickscorp** [whatyouhide/corsica#49]
In the readme, one of the example regexp is `~r{^https?://(.*\.?)foo\.com$}`. It could be very misleading for beginners - as it lets things like `anotherfoo.com` through, while the effort put in the `(.*\.?)` part really *seems* to require *anything and then a dot*, while it's not the case. It's quite bad, because an attacker could register that domain.

It also allows for `.foo.com`, but it's not that bad because an attacker couldn't register that domain.

Maybe we could replace it by `~r{^https?://(.*\.)?foo\.com$}` ?

**Comment by whatyouhide** [comment]
Yep, PR is welcome. I clearly didn't put much effort into that regex :P Good catch, thanks!

**Comment by hickscorp** [comment]
Thanks @whatyouhide. Sure thing - I've issued a very tiny PR ;)
