### ISSUE TITLE
Support Access-Control-Allow-Private-Network in preflight request

### ISSUE THREAD

**Issue by wchenNL** [whatyouhide/corsica#62]
Latest Chrome (Version 106.0.5249.119 (Official Build) (x86_64))  now sends a preflight request which expects a `Access-Control-Allow-Private-Network` header in the response.

https://developer.chrome.com/blog/private-network-access-preflight/

Is it possible to support this?

We are using Corsica in our endpoint.ex
```
  plug Corsica,
    origins: [
      "http://localhost:3000"
    ],
    log: [rejected: :error, invalid: :warn, accepted: :debug],
    allow_headers: ["content-type", "authorization"],
    allow_credentials: true
```

Ideally, have an option like below would be great:
```
  plug Corsica,
    origins: [
      "http://localhost:3000"
    ],
    log: [rejected: :error, invalid: :warn, accepted: :debug],
    allow_headers: ["content-type", "authorization"],
    allow_credentials: true,
    allow_private_network: true
```

**Comment by whatyouhide** [comment]
Just took a look at the [spec draft](https://wicg.github.io/private-network-access/#http-headerdef-access-control-allow-private-network) and yeah, that sounds good. Any chance you'd want to work on a PR to support the option? 🙃

**Comment by wchenNL** [comment]
@whatyouhide I have the change locally now, can you grant me permission to create the PR?
