### ISSUE TITLE
in put_cors_simple_resp_headers, log method throws "key :accepted not found in: []"

### ISSUE THREAD

**Issue by FFdhorkin** [whatyouhide/corsica#64]
We're having a weird issue probably related to this: https://github.com/whatyouhide/corsica/commit/6d9b90f1087501cfc4a243ebafbc976a9f7c5085

Other than upgrading our Corsica version, I don't think this is caused by our code, and release notes don't seem to mention any breaking changes.

```
\** (exit) an exception was raised:
    ** (KeyError) key :accepted not found in: []
        (elixir 1.14.2) lib/keyword.ex:595: Keyword.fetch!/2
        (corsica 1.3.0) lib/corsica.ex:774: Corsica.log/3
        (corsica 1.3.0) lib/corsica.ex:499: Corsica.put_cors_simple_resp_headers/2
        (gateway 1.3.2-1) lib/gateway/router/portal.ex:7: Gateway.Router.Portal.plug_builder_call/2
```

**Comment by whatyouhide** [comment]
@FFdhorkin that's interesting yeah, definitely shouldn't happen! Can you show me how you're using Corsica in your Plug pipeline?

**Comment by FFdhorkin** [comment]
> @FFdhorkin that's interesting yeah, definitely shouldn't happen! Can you show me how you're using Corsica in your Plug pipeline?

I'm not an elixir dev, just trying to upgrade dependencies for a project that uses elixir. So if you could be more specific (or provide an example), that would help me pin down what you're looking for.

We're currently on 1.3.0; we were on 1.1.3 before I started touching stuff.

Taking a guess, though:
`plug(Corsica, origins: "*", allow_methods: :all, allow_headers: :all)`

I don't think this is what you're asking, but the other place we're referencing Corsica looks like this:
```
      opts = %Corsica.Options{
        origins: "*",
        allow_methods: :all,
        allow_headers: :all
      }

      Corsica.call(conn, opts)
```

**Comment by whatyouhide** [comment]
Okay, this makes sense. The issue here is that you cannot use the `%Corsica.Options{}` struct directly. It's **not documented**, and it's part of the internal workings of Corsica itself. The `Gateway.Cors` plug you mention **must not** call `Corsica` directly (with `Corsica.call/2`, especially if you already have `plug Corsica, ...` somewhere else.

Hopefully that makes sense. Happy to answer more questions, but this is not an issue in Corsica after all 🙃

**Comment by FFdhorkin** [comment]
> Okay, this makes sense. The issue here is that you cannot use the `%Corsica.Options{}` struct directly. It's **not documented**, and it's part of the internal workings of Corsica itself. The `Gateway.Cors` plug you mention **must not** call `Corsica` directly (with `Corsica.call/2`, especially if you already have `plug Corsica, ...` somewhere else.
> 
> Hopefully that makes sense. Happy to answer more questions, but this is not an issue in Corsica after all 🙃

Make sense that if previous devs on this project were using undocumented inner workings, things could break after an upgrade.

Can Corsica.Router be configured at runtime? I tried a fix based on the Corsica.Router example in your docs, but looking on the warning I got, it looks like that `use Corsica.Router` bit is compile-time, not run-time, and I don't see anything in the docs that suggest a dynamic config is possible without one of the approaches [here](https://akoutmos.com/post/plug-runtime-config/).

**Comment by whatyouhide** [comment]
@FFdhorkin `Plug.Router` cannot be configured at runtime for all of its properties, no. You can configure the `:origins` dynamically (through a function), but not the rest.

If you need other options to be dynamic, then you can use `Plug.run/2` inside your own plugs to properly call the `init/1` and `call/2` callbacks.
