### ISSUE TITLE
PLTs are included in hex package

### ISSUE THREAD

**Issue by aaronrenner** [whatyouhide/corsica#68]
I just noticed that the PLTs that are store in `priv/plts` are making their way into the published hex package.

<img width="1224" alt="Screenshot 2023-10-17 at 7 02 38 AM" src="https://github.com/whatyouhide/corsica/assets/120878/5580527b-f47c-48e5-99fe-698e3ec36982">

https://preview.hex.pm/preview/corsica/2.1.2

I'm guessing this is unintentional and I'm wondering if you'd mind excluding them from the release so we can save a couple MB when building our docker images.

**Comment by whatyouhide** [comment]
Released v2.1.3. Great catch, thanks for reporting! 💟
