### ISSUE TITLE
The regexp example is dangerously permissive

### ISSUE THREAD

**Issue by jub0bs** [whatyouhide/corsica#70]
The documentation contains [the following example](https://github.com/whatyouhide/corsica/blob/2cfc4fd70bd8ede11fffcdb825ca53fd237e4dd6/lib/corsica.ex#L63):

```elixir
plug Corsica, origins: ~r{^https?://(.*\.?)foo\.com$}
```

Presumably, it's designed to capture all Web origins whose host is exactly `foo.com` or some direct subdomain of `foo.com` (e.g. `bar.foo.com`), and reject all other Web origins.

However, the backslashes don't get rendered in the [generated documentation](https://hexdocs.pm/corsica/Corsica.html#module-options): 

```elixir
plug Corsica, origins: ~r{^https?://(.*.?)foo.com$}
```

This may mislead users into thinking that such a regexp is safe, but it's too permissive: it indeed [matches](https://regex101.com/r/t4GyJz/1) Web origins like `https://attacker-foo.com`. You should make sure that backslashes are retained in the generated doc.

Actually, even if the backslashes are retained, the regexp remains too permissive. Because the `?` only applies to the literal `.`, the regexp still [matches](https://regex101.com/r/mR5Dpq/1) Web origins like `https://attacker-foo.com`. Instead, it should probably be

```elixir
plug Corsica, origins: ~r{^https?://(.*\.)?foo\.com$}
```

(Note that the second `?` now applies to the capturing group rather than just the literal `.`.)

**Comment by jub0bs** [comment]
Related: #49

**Comment by whatyouhide** [comment]
Nice yep! To make this render correctly we just need to turn `"""` into `~S"""` at the start of the module doc. @jub0bs would you be able to send a PR? 🙃

**Comment by jub0bs** [comment]
@whatyouhide I'm hesitant to contribute a PR, as I'm not well-versed in Elixir. I just wanted to highlight the issue. 😇

**Comment by jub0bs** [comment]
@whatyouhide Fast turnaround! 💪
