### ISSUE TITLE
The recap table on CORS response headers needs some love

### ISSUE THREAD

**Issue by jub0bs** [whatyouhide/corsica#71]
Here is the recap table on CORS response headers at the end of [the _Options_ section in the documentation](https://hexdocs.pm/corsica/Corsica.html#module-options):

```
  | Header                                 | Request Type      | Presence in the Response       |
  |----------------------------------------|-------------------|--------------------------------|
  | `access-control-allow-origin`          | simple, preflight | always                         |
  | `access-control-allow-headers`         | preflight         | always                         |
  | `access-control-allow-credentials`     | preflight         | `allow_credentials: true`      |
  | `access-control-allow-private-network` | preflight         | `allow_private_network: true`  |
  | `access-control-expose-headers`        | preflight         | `:expose_headers` is not empty |
  | `access-control-max-age`               | preflight         | `:max_age` is present          |
```

However, it's incomplete (it lacks a row for the `access-control-allow-methods` header) and somewhat inaccurate:

* [`access-control-allow-credentials`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Credentials) needs to be present in both responses (to the preflight and actual requests) for credentialed access to work, and
* [`access-control-expose-headers`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Expose-Headers) is only ever useful in the response to the _actual_ request.

Finally, I recommend the term _actual request_ (i.e. the request actually issued by the client) rather than [_simple_ request](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS#simple_requests) (a.k.a. "non-preflighted request").

Unless I'm missing something, here is what I believe the first two columns of that table should look like:

```
 | Header                                 | Request Type      | 
 |----------------------------------------|-------------------|
 | `access-control-allow-origin`          | actual, preflight |
 | `access-control-allow-methods`         | preflight         |
 | `access-control-allow-headers`         | preflight         |
 | `access-control-allow-credentials`     | actual, preflight |
 | `access-control-allow-private-network` | preflight         |
 | `access-control-expose-headers`        | actual            |
 | `access-control-max-age`               | preflight         | 
```

**Comment by whatyouhide** [comment]
Thanks @jub0bs, fixed 💯

**Comment by jub0bs** [comment]
@whatyouhide Close, but be careful: the second column for `access-control-expose-headers` should be `actual`, not `preflight`.
