### ISSUE TITLE
Can't get Corsica to respond to pre-flight requests 

### ISSUE THREAD

**Issue by ianwalter** [whatyouhide/corsica#8]
Created this module:
```elixir
defmodule ExampleApp.CORS do
  use Corsica.Router, origins: "*", log: :debug
  
  resource "/*"
end
```
And added it to the endpoint before the router:
```elixir
  plug ExampleApp.CORS
  plug ExampleApp.Router
```
Still, I'm getting a connection refused on OPTIONS requests to `/v1/sessions`. Any ideas on what I'm doing wrong? I'm not seeing anything in the logs and I'm using Plug v1.0.2. This seems like the latest version but the README lists 1.1 as the dependency?

**Edit:** Also, I'm using Phoenix v1.0.3.

**Comment by ianwalter** [comment]
My bad, turns out I had some left over pfctl rules that were doing some re-routing.
Still, should Plug's version be updated in the README?

**Comment by whatyouhide** [comment]
@ianwalter hey, ops yes that's a mistake in the README :). It should be `~> 1.0`. Want to send a PR or do you prefer me to take care of it?
